name: deep_pytorch
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyterlab
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - transformers==4.46.3
      - diffusers==0.33.1
      - accelerate
      - safetensors
      - huggingface_hub<1.0
      - imageio
      - imageio-ffmpeg
